"""add_mode_column_to_quiz_attempts

Revision ID: caff5d494f9d
Revises: c1d2e3f4g5h6
Create Date: 2025-11-21 03:24:11.588816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caff5d494f9d'
down_revision: Union[str, None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable with default value
    op.add_column('quiz_attempts', sa.Column('mode', sa.String(), nullable=True, server_default='practice'))

    # Step 2: Update existing NULL values to 'practice'
    op.execute("UPDATE quiz_attempts SET mode = 'practice' WHERE mode IS NULL")

    # Step 3: Make column NOT NULL
    op.alter_column('quiz_attempts', 'mode', nullable=False)

    # Step 4: Add check constraint with quoted column name (avoid PostgreSQL aggregate function conflict)
    op.execute('ALTER TABLE quiz_attempts ADD CONSTRAINT check_mode_valid CHECK ("mode" IN (\'study\', \'practice\'))')

    # Step 5: Create indexes
    op.create_index('idx_quiz_user_mode', 'quiz_attempts', ['user_id', 'mode'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_mode'), 'quiz_attempts', ['mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_mode'), table_name='quiz_attempts')
    op.drop_index('idx_quiz_user_mode', table_name='quiz_attempts')
    op.execute('ALTER TABLE quiz_attempts DROP CONSTRAINT IF EXISTS check_mode_valid')
    op.drop_column('quiz_attempts', 'mode')
    # ### end Alembic commands ###
