"""Add gamification system: quiz tracking, achievements, and avatars

Revision ID: ee7ad33dca0c
Revises: 
Create Date: 2025-11-17 22:51:17.538560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7ad33dca0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix circular dependency: Create avatars first without FK, then achievements, then add FK

    # Step 1: Create avatars table WITHOUT foreign key to achievements
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('required_achievement_id', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_avatars_id'), 'avatars', ['id'], unique=False)

    # Step 2: Create achievements table WITH foreign key to avatars (now exists)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('badge_icon_url', sa.String(), nullable=True),
    sa.Column('criteria_type', sa.String(), nullable=False),
    sa.Column('criteria_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('unlocks_avatar_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('criteria_value > 0', name='check_criteria_value_positive'),
    sa.CheckConstraint('xp_reward >= 0', name='check_xp_reward_non_negative'),
    sa.ForeignKeyConstraint(['unlocks_avatar_id'], ['avatars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_achievement_criteria_type', 'achievements', ['criteria_type'], unique=False)
    op.create_index(op.f('ix_achievements_criteria_type'), 'achievements', ['criteria_type'], unique=False)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)

    # Step 3: Add foreign key constraint from avatars to achievements (now both exist)
    op.create_foreign_key(
        'fk_avatars_required_achievement',
        'avatars', 'achievements',
        ['required_achievement_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('correct_answers <= total_questions', name='check_correct_not_exceeds_total'),
    sa.CheckConstraint('correct_answers >= 0', name='check_correct_answers_non_negative'),
    sa.CheckConstraint('score_percentage >= 0 AND score_percentage <= 100', name='check_score_percentage_range'),
    sa.CheckConstraint('time_taken_seconds >= 0', name='check_time_taken_non_negative'),
    sa.CheckConstraint('total_questions > 0', name='check_total_questions_positive'),
    sa.CheckConstraint('xp_earned >= 0', name='check_xp_earned_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_exam_score_date', 'quiz_attempts', ['exam_type', 'score_percentage', 'completed_at'], unique=False)
    op.create_index('idx_quiz_user_date', 'quiz_attempts', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_completed_at'), 'quiz_attempts', ['completed_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_exam_type'), 'quiz_attempts', ['exam_type'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('progress_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_index('idx_user_achievement_user_earned', 'user_achievements', ['user_id', 'earned_at'], unique=False)
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_earned_at'), 'user_achievements', ['earned_at'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_avatars',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'avatar_id')
    )
    op.create_index('idx_user_avatar_user', 'user_avatars', ['user_id', 'unlocked_at'], unique=False)
    op.create_index(op.f('ix_user_avatars_avatar_id'), 'user_avatars', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_user_avatars_user_id'), 'user_avatars', ['user_id'], unique=False)
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.String(length=1), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("correct_answer IN ('A', 'B', 'C', 'D')", name='check_correct_answer_valid'),
    sa.CheckConstraint("user_answer IN ('A', 'B', 'C', 'D')", name='check_user_answer_valid'),
    sa.CheckConstraint('time_spent_seconds >= 0', name='check_time_spent_non_negative'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_answer_attempt', 'user_answers', ['quiz_attempt_id', 'is_correct'], unique=False)
    op.create_index('idx_user_answer_question_correct', 'user_answers', ['question_id', 'is_correct'], unique=False)
    op.create_index('idx_user_answer_user_correct', 'user_answers', ['user_id', 'is_correct'], unique=False)
    op.create_index(op.f('ix_user_answers_id'), 'user_answers', ['id'], unique=False)
    op.create_index(op.f('ix_user_answers_is_correct'), 'user_answers', ['is_correct'], unique=False)
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_quiz_attempt_id'), 'user_answers', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_user_answers_user_id'), 'user_answers', ['user_id'], unique=False)
    # Add new gamification columns to user_profiles
    # Use server_default for existing rows (set to 0 for xp, 1 for level)
    op.add_column('user_profiles', sa.Column('selected_avatar_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_profiles', sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_user_profiles_selected_avatar', 'user_profiles', 'avatars', ['selected_avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'level')
    op.drop_column('user_profiles', 'xp')
    op.drop_column('user_profiles', 'selected_avatar_id')
    op.drop_index(op.f('ix_user_answers_user_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_quiz_attempt_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_is_correct'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_id'), table_name='user_answers')
    op.drop_index('idx_user_answer_user_correct', table_name='user_answers')
    op.drop_index('idx_user_answer_question_correct', table_name='user_answers')
    op.drop_index('idx_user_answer_attempt', table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_user_avatars_user_id'), table_name='user_avatars')
    op.drop_index(op.f('ix_user_avatars_avatar_id'), table_name='user_avatars')
    op.drop_index('idx_user_avatar_user', table_name='user_avatars')
    op.drop_table('user_avatars')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_earned_at'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_index('idx_user_achievement_user_earned', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_exam_type'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_completed_at'), table_name='quiz_attempts')
    op.drop_index('idx_quiz_user_date', table_name='quiz_attempts')
    op.drop_index('idx_quiz_exam_score_date', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_avatars_id'), table_name='avatars')
    op.drop_table('avatars')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_criteria_type'), table_name='achievements')
    op.drop_index('idx_achievement_criteria_type', table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
